-- 邮件通知：七类提醒由管理员在设置里逐类勾选（另有总开关），不在代码里写死组织偏好。
-- 待办类（默认开启）：待财委审批→财委、待主席审批→主席、待付款登记→付款登记身份、
-- 退回修改→申请人（要改完重新提交）、待补充收款码→申请人（要上传收款码，邮件文案即"已通过审批"）。
-- 结果类（默认关闭，管理员需要时打开）：拒绝申请→申请人、已付款→申请人。
-- 已撤回、草稿两类状态永远不发（没有待办也不是结果）。
-- 发送由 app-api 的 send_notifications 消费（管理员手动或定时任务）；邮件服务密钥只保存在 Edge Function 环境变量中，不进入前端、数据库或仓库。
-- 队列状态变化全部走带租约的原子领取，避免重复寄信。
-- 执行顺序：本文件依赖 supabase/admin-settings-audit.sql 里的 private.app_insert_user（该文件尚未收进 migrations/），
-- 以及 supabase/member-management-and-resubmission.sql 里的 public.app_list_members。请先执行那两个文件，再执行本迁移。
do $$
begin
  if to_regprocedure('private.app_insert_user(text,text,text,text)') is null then
    raise exception '缺少 private.app_insert_user：请先执行 supabase/admin-settings-audit.sql（再执行 supabase/member-management-and-resubmission.sql），然后重跑本迁移';
  end if;
  -- 本文件在运行期还会调用这两个函数（建号时分配角色、身份判定），同样先检查：
  -- plpgsql 函数体建函数时不解析引用，缺了不会在迁移时报错，会拖到有人点按钮才炸。
  if to_regprocedure('public.app_set_member_roles(uuid,uuid,text[],boolean)') is null then
    raise exception '缺少 public.app_set_member_roles：请先执行 supabase/member-management-and-resubmission.sql，然后重跑本迁移';
  end if;
  if to_regprocedure('private.app_user_has_role(uuid,text)') is null then
    raise exception '缺少 private.app_user_has_role：请先执行 supabase/migrations/20261002133000_separate_admin_and_workflow_roles.sql，然后重跑本迁移';
  end if;
end $$;

-- 真实邮箱存放在 app_users.email。遗留的 profiles.email 由 private.app_insert_user 写入的是用户名占位值，
-- 通知功能不使用它，也不要把它当收件人地址来源。
alter table public.app_users add column if not exists email text;
alter table public.app_users drop constraint if exists app_users_email_check;
alter table public.app_users add constraint app_users_email_check
  check (email is null or (char_length(email) <= 254 and email ~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'));

alter table public.settings add column if not exists email_notify_enabled boolean not null default false;
-- 逐类勾选：提醒类型是组织偏好，放进配置而不是写死在代码里。
-- 默认只开"需要有人动手"的五类待办；拒绝申请、已付款是结果通知，默认关，管理员需要时在设置里打开。
-- 白名单与 notifications.event 的 check 约束保持一致（两边同时改）。
alter table public.settings add column if not exists email_notify_events text[] not null default array['待财委审批','待主席审批','退回修改','待补充收款码','待付款登记'];
-- 更早的中间版本可能留下过同名列（没有默认值、可为空）：显式补默认值与非空，
-- 否则触发器的 `target_event = any(email_notify_events)` 会得到 NULL、静默一封都不发。
alter table public.settings alter column email_notify_events set default array['待财委审批','待主席审批','退回修改','待补充收款码','待付款登记'];
update public.settings set email_notify_events = array['待财委审批','待主席审批','退回修改','待补充收款码','待付款登记'] where email_notify_events is null;
alter table public.settings alter column email_notify_events set not null;
-- 老库里若已有七类之外的值，直接加约束只会报一句 "violated by some row"；先给出可操作的报错（列出具体取值），
-- 不静默改配置。历史行处理完再重跑本迁移即可。
do $$
declare offenders text;
begin
  select string_agg(distinct item, '、') into offenders
  from public.settings s, unnest(s.email_notify_events) item
  where item not in ('待财委审批','待主席审批','退回修改','待补充收款码','待付款登记','拒绝申请','已付款');
  if offenders is not null then
    raise exception 'settings.email_notify_events 里有不在支持列表中的类型（%）：请先在设置里改成合法类型再重跑本迁移', offenders;
  end if;
end $$;
alter table public.settings drop constraint if exists settings_email_notify_events_check;
alter table public.settings add constraint settings_email_notify_events_check
  check (email_notify_events is not null
    and email_notify_events <@ array['待财委审批','待主席审批','退回修改','待补充收款码','待付款登记','拒绝申请','已付款']);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  application_id uuid not null references public.applications(id) on delete cascade,
  application_version integer not null,
  event text not null check (event in ('待财委审批','待主席审批','退回修改','待补充收款码','待付款登记','拒绝申请','已付款')),
  recipient_user_id uuid not null references public.app_users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','sending','sent','failed','cancelled')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  lease_expires_at timestamptz not null default now(),
  claim_id uuid,
  last_error text not null default '',
  created_at timestamptz not null default now(),
  sent_at timestamptz
);
-- 上一版队列没有 sending 状态与租约列；下面的语句让本文件对已执行过旧版的库同样成立。
alter table public.notifications drop constraint if exists notifications_status_check;
alter table public.notifications add constraint notifications_status_check check (status in ('pending','sending','sent','failed','cancelled'));
alter table public.notifications drop constraint if exists notifications_attempts_check;
alter table public.notifications add constraint notifications_attempts_check check (attempts >= 0);
alter table public.notifications add column if not exists lease_expires_at timestamptz not null default now();
alter table public.notifications add column if not exists claim_id uuid;
-- 事件集合是七类：五类"需要有人动手"的待办 + 拒绝申请/已付款两个结果通知（默认关）。
-- 对已执行过旧版（七类或五类）的库同样收敛到这一份名单；历史行里若有七类之外的事件名，
-- 先给出可操作的报错（列出具体取值），而不是让约束抛一句难懂的 "violated by some row"。
do $$
declare offenders text;
begin
  select string_agg(distinct event, '、') into offenders
  from public.notifications
  where event not in ('待财委审批','待主席审批','退回修改','待补充收款码','待付款登记','拒绝申请','已付款');
  if offenders is not null then
    raise exception 'notifications.event 里有不在支持列表中的值（%）：请先处理这些历史行（例如改成 cancelled 并留档）再重跑本迁移', offenders;
  end if;
end $$;
alter table public.notifications drop constraint if exists notifications_event_check;
alter table public.notifications add constraint notifications_event_check check (event in ('待财委审批','待主席审批','退回修改','待补充收款码','待付款登记','拒绝申请','已付款'));

-- 去重键是“部分唯一索引”而不是唯一约束：cancelled（提醒已作废）的行不参与去重。
-- 这样同一版本内“收款码被移除 → 重新提交”可以再次提醒付款登记人，而重复进入同一状态仍然只留一封。
-- 已执行过旧版的库上还留着旧去重约束；只删“列正好是这四列”的那一个，不误伤将来新增的唯一约束。
do $$
declare item record;
begin
  for item in
    select c.conname from pg_constraint c
    where c.conrelid = 'public.notifications'::regclass and c.contype = 'u'
      and (
        -- pg_attribute.attname 是 name 类型：不显式转成 text，右侧的 text[] 字面量会让整条查询在
        -- 解析期报 operator does not exist: name[] = text[]（即使表上没有任何旧唯一约束也照样报）。
        select array_agg(a.attname::text order by a.attname)
        from unnest(c.conkey) as k(attnum)
        join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.attnum
      ) = array['application_id','application_version','event','recipient_user_id']
  loop
    execute format('alter table public.notifications drop constraint %I', item.conname);
  end loop;
end $$;
drop index if exists notifications_dedupe_idx;
create unique index if not exists notifications_dedupe_idx
  on public.notifications(application_id, application_version, event, recipient_user_id)
  where status <> 'cancelled';

drop index if exists notifications_due_idx;
create index if not exists notifications_pending_idx on public.notifications(next_attempt_at) where status = 'pending';
create index if not exists notifications_lease_idx on public.notifications(lease_expires_at) where status = 'sending';
create index if not exists notifications_application_idx on public.notifications(application_id);
alter table public.notifications enable row level security;
revoke all on table public.notifications from public, anon, authenticated;

-- 状态 ↔ 提醒事件的映射在数据库里只写一份，入队触发器与投递前复核都问它：
-- 触发器问“这个新状态该发哪类提醒”，投递前复核问“这封提醒对应的待办现在是否仍然成立”
-- （app-api 侧另有一份 JS 副本用于发送前的兜底判断，测试逐项比对两份清单）。
-- 写成 VALUES 表而不是 CASE，是因为 app-api 的 NOTIFY_EVENT_STATUS 本来就是这张两列表，
-- 形状一致时“两份清单错位”在测试里读起来更直观；已撤回、草稿不在表里，永远不发。
create or replace function private.app_notify_event_for_status(p_status text)
returns text language sql immutable set search_path = public, pg_temp as $$
  select m.event
  from (values
    ('finance_pending', '待财委审批'),
    ('chair_pending', '待主席审批'),
    ('changes_requested', '退回修改'),
    ('payment_info_required', '待补充收款码'),
    ('payment_pending', '待付款登记'),
    ('rejected', '拒绝申请'),
    ('paid', '已付款')
  ) as m(status, event)
  where m.status = p_status;
$$;
revoke all on function private.app_notify_event_for_status(text) from public, anon, authenticated;

-- 状态变化、总开关与逐类开关在同一个事务里决定是否入队；已撤回、草稿不在映射表里，永远不发。
-- 五类待办发给对应处理身份的成员（并排除申请人本人）或申请人本人；拒绝申请、已付款两个结果通知只发给申请人本人。
-- 收件人一律通过 private.app_user_has_role 判定，这样身份含义变化（例如付款登记视同财委）不需要改动这里。
create or replace function private.enqueue_email_notification()
returns trigger language plpgsql security definer set search_path = public, private, pg_temp as $$
declare target_event text;
begin
  if old.status is not distinct from new.status then return null; end if;

  -- 收款码被移除会把付款退回“待补充收款码”：本轮的“待付款登记”提醒随之作废——它指向的收款人已经变了，
  -- 不能再用旧收款信息催付款。作废（cancelled）后不参与去重，同一版本内重新提交收款码可以再次提醒付款登记人；
  -- 若作废前已经发出过一次，sent_at 仍保留，管理面板能看到它确实寄出过。
  if old.status = 'payment_pending' and new.status = 'payment_info_required' then
    update public.notifications
       set status = 'cancelled', claim_id = null, lease_expires_at = now(),
           last_error = left('收款信息已变更，本次待付款登记提醒作废' ||
             case when sent_at is null then '' else '（作废前已发出过一次）' end, 300)
     where application_id = new.id and application_version = old.version
       and event = '待付款登记' and status <> 'cancelled';
  end if;

  target_event := private.app_notify_event_for_status(new.status);
  if target_event is null then return null; end if;
  -- 总开关与该类型的勾选都要为真；关闭期间发生的变化不补发（管理员重新打开后只管之后的状态变化）。
  if not exists(select 1 from public.settings where id = 1 and email_notify_enabled and target_event = any(email_notify_events)) then return null; end if;
  insert into public.notifications(application_id, application_version, event, recipient_user_id)
  select new.id, new.version, target_event, u.id
  from public.app_users u
  where u.active
    and coalesce(u.email, '') <> ''
    and case target_event
      when '待财委审批' then u.id <> new.owner_id and private.app_user_has_role(u.id, 'finance')
      when '待主席审批' then u.id <> new.owner_id and private.app_user_has_role(u.id, 'chair')
      when '待付款登记' then u.id <> new.owner_id and private.app_user_has_role(u.id, 'cashier')
      else u.id = new.owner_id
    end
  on conflict (application_id, application_version, event, recipient_user_id) where status <> 'cancelled' do nothing;
  return null;
end $$;
drop trigger if exists email_notify_status_change on public.applications;
create trigger email_notify_status_change after update of status on public.applications
  for each row execute function private.enqueue_email_notification();
revoke all on function private.enqueue_email_notification() from public, anon, authenticated;

-- 消费前复核收件人是否仍然合格：角色被撤销、账号被停用或邮箱被解绑之后，这个待办已经不属于他，
-- 继续寄出等于把申请人、部门与金额发给已经没有查看权限的人。判定必须继续走 private.app_user_has_role
-- （与入队、与站内权限同一处语义），这样"付款登记视同财委"这类身份变化自动生效。
create or replace function private.app_notify_recipient_allowed(p_user_id uuid, p_event text)
returns boolean language sql stable security definer set search_path = public, private, pg_temp as $$
  select exists(
    select 1 from public.app_users u
    where u.id = p_user_id
      and u.active
      and coalesce(u.email, '') <> ''
      and case p_event
        when '待财委审批' then private.app_user_has_role(u.id, 'finance')
        when '待主席审批' then private.app_user_has_role(u.id, 'chair')
        when '待付款登记' then private.app_user_has_role(u.id, 'cashier')
        else true
      end
  );
$$;
revoke all on function private.app_notify_recipient_allowed(uuid, text) from public, anon, authenticated;

-- 原子领取一轮队列：先丢弃超龄提醒，再把上次中断的 sending 行退回队列（同样受失败上限与超龄约束），
-- 然后作废收件人已不合格或版本已过期的提醒，最后带租约领取到期的 pending 行。
-- p_claim_id 由调用方生成，写回结果时必须同时匹配 id、status='sending' 和 claim_id，
-- 这样两个发送方（管理员手动点击与定时任务）不会重复寄同一封邮件，中断的批次也不会永久卡住。
-- p_max_attempts 与调用方（app-api 的 NOTIFY_MAX_ATTEMPTS）保持一致：中断恢复与投递失败共用同一个上限。
-- 本文件的前一版是四参数签名，先按函数名删掉所有重载，避免 PostgREST 命名参数调用出现歧义。
do $$
declare item record;
begin
  for item in
    select p.oid, p.proname from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'app_claim_notifications'
  loop
    execute format('drop function public.%I(%s)', item.proname, pg_get_function_identity_arguments(item.oid));
  end loop;
end $$;
create or replace function public.app_claim_notifications(p_claim_id uuid, p_limit integer, p_lease_seconds integer, p_max_age_hours integer, p_max_attempts integer default 5)
returns jsonb language plpgsql security definer set search_path = public, private, pg_temp as $$
declare claimed jsonb; discarded integer; aged integer; cancelled integer; revoked integer; disabled integer; taken integer;
begin
  if p_claim_id is null then raise exception '缺少领取批次号'; end if;
  if p_limit is null or p_limit < 1 or p_limit > 200 then raise exception '领取数量无效'; end if;
  if p_lease_seconds is null or p_lease_seconds < 30 or p_lease_seconds > 900 then raise exception '发送租约无效'; end if;
  if p_max_age_hours is null or p_max_age_hours < 1 or p_max_age_hours > 168 then raise exception '队列有效期无效'; end if;
  if p_max_attempts is null or p_max_attempts < 1 or p_max_attempts > 10 then raise exception '失败重试上限无效'; end if;

  -- 开关关闭期间积压的提醒不再补发：重新开启时突然寄出几天前的邮件会让成员困惑。
  update public.notifications
     set status = 'failed', last_error = '超过 ' || p_max_age_hours || ' 小时未发送，已丢弃'
   where status = 'pending' and created_at < now() - make_interval(hours => p_max_age_hours);
  get diagnostics discarded = row_count;

  -- 上次进程被中断（函数超时或被杀）留下的 sending 行，按三种去向处理：
  --   1) 已超龄：直接判丢弃，并计入 discarded（与第 1 步的超龄 pending 同一个统计口径，审计不会少报）；
  --   2) 已经用满尝试次数：判永久失败（与普通投递失败走同一个上限与文案）；
  --   3) 其余：计入一次尝试后退回队列。
  update public.notifications
     set status = 'failed', attempts = attempts + 1, claim_id = null, lease_expires_at = now(),
         last_error = left('超过 ' || p_max_age_hours || ' 小时未发送，已丢弃', 300)
   where status = 'sending' and lease_expires_at <= now()
     and created_at < now() - make_interval(hours => p_max_age_hours);
  get diagnostics aged = row_count;
  discarded := discarded + aged;

  update public.notifications
     set status = 'failed', attempts = attempts + 1, claim_id = null, lease_expires_at = now(),
         last_error = left('连续 ' || (attempts + 1) || ' 次发送未完成，已停止重试', 300)
   where status = 'sending' and lease_expires_at <= now()
     and attempts + 1 >= p_max_attempts;

  update public.notifications
     set status = 'pending', attempts = attempts + 1, claim_id = null, next_attempt_at = now(),
         last_error = left(case when last_error = '' then '上一次发送未完成，已重新排队'
                                else '上一次发送未完成，已重新排队 | ' || last_error end, 300)
   where status = 'sending' and lease_expires_at <= now();

  -- 发送前复核收件人：角色被撤销、账号被停用或邮箱被解绑之后，这个待办已经不属于他，
  -- 继续寄出等于把申请人、部门与金额发给已经没有查看权限的人。作废（cancelled）不参与去重，
  -- 身份恢复且待办再次出现时还能重新提醒。只碰 pending：别人正在发送的行不能被这里抢标签。
  update public.notifications n
     set status = 'cancelled', claim_id = null, lease_expires_at = now(),
         last_error = '收件人已不具备该待办的处理身份，提醒已作废'
   where n.status = 'pending' and not private.app_notify_recipient_allowed(n.recipient_user_id, n.event);
  get diagnostics cancelled = row_count;

  -- 发送前复核版本：申请被退回修改后重新提交会升 version，旧版本的提醒指向的是上一次待办。
  -- 状态可能绕一圈回到同一个值（finance_pending → changes_requested → finance_pending），只比状态认不出来，
  -- 于是同一件事会连发两封。版本不一致的 pending 行就地作废（handler 侧还会对领取后变化的版本再核一次）。
  update public.notifications n
     set status = 'cancelled', claim_id = null, lease_expires_at = now(),
         last_error = '申请已重新提交（版本 ' || n.application_version || ' → ' || a.version || '），提醒已作废'
    from public.applications a
   where a.id = n.application_id and a.version <> n.application_version
     and n.status = 'pending';
  get diagnostics revoked = row_count;
  cancelled := cancelled + revoked;

  -- 管理员在设置里关掉某一类提醒后，已经积压但尚未投递的该类行就地作废，不再寄出。
  -- （总开关关闭时不调用本函数：app-api 直接返回 skipped，积压行留给 24 小时超龄丢弃。）
  update public.notifications n
     set status = 'cancelled', claim_id = null, lease_expires_at = now(),
         last_error = '管理员已关闭「' || n.event || '」提醒，本封已作废'
   where n.status = 'pending'
     and not exists(select 1 from public.settings s where s.id = 1 and n.event = any(s.email_notify_events));
  get diagnostics disabled = row_count;
  cancelled := cancelled + disabled;

  update public.notifications
     set status = 'sending', lease_expires_at = now() + make_interval(secs => p_lease_seconds), claim_id = p_claim_id
   where id in (
     select due.id from (
       select id
       from public.notifications
       where status = 'pending' and next_attempt_at <= now()
       order by created_at, id
       limit p_limit
       for update skip locked
     ) due
   );
  get diagnostics taken = row_count;

  select coalesce(jsonb_agg(jsonb_build_object(
           'id', id, 'application_id', application_id, 'application_version', application_version,
           'event', event, 'recipient_user_id', recipient_user_id, 'attempts', attempts, 'last_error', last_error) order by created_at, id), '[]'::jsonb)
    into claimed
  from public.notifications
  where claim_id = p_claim_id and status = 'sending';

  return jsonb_build_object('discarded', discarded, 'cancelled', cancelled, 'claimed', taken, 'rows', claimed);
end $$;

-- 投递前最后一次复核（PR #19 终审 P2 起改为“白名单”契约）：app-api 在每个发送组之前调用，
-- 请求里的每个 id 都必须拿到明确的 'send' 判定，handler 才会把这封交给邮件服务。
--
-- 旧版是 blocked 契约：只返回"不该再发"的行，handler 把"没出现在结果里"当成放行。于是领取之后被工作流
-- 改成 cancelled 的行（例如移除收款码会把「待付款登记」作废）从结果里消失，反而被当成合格行寄出——
-- 缺席不能作为放行证据。现在三种判定都由数据库给出，客户端不重写规则：
--   send   —— 仍属于本次领取、租约未过期，且申请版本/状态、收件人身份、逐类开关全部仍然成立：唯一放行值。
--   cancel —— 仍属于本次领取，但按数据库当前事实不该再发（类型被关、身份失效、申请已升版本或已离开该状态）：
--             handler 就地写 cancelled 并计「已作废」。
--   skip   —— 已经不属于本次领取（状态不是 sending、批次号不是本批、租约已过期）：不投递，复核也不会把它改成
--             cancelled/failed。它可能刚被工作流作废、被别的批次接手或正在等租约恢复，写回只会破坏别的路径的
--             记账。（handler 收尾退回队列时仍会碰"本批持有、只是租约已过期"的那种 skip——那是既有的中断恢复
--             语义；其余 skip 在写回条件上必然不命中。）
-- 只逐项检查请求里给出的 id（不按表扫）；left join 容忍申请已被删除（行会随级联一起消失，
-- 那种情况下 id 根本不出现在返回结果里，handler 按“没有明确放行”处理）。
-- 总开关（email_notify_enabled）不参与：它是暂停（下一轮直接 skipped），不是作废理由。
-- 旧版函数按函数名整体删除，避免库里留下两个复核入口。
do $$
declare item record;
begin
  for item in
    select p.oid, p.proname from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'app_notify_blocked_rows'
  loop
    execute format('drop function public.%I(%s)', item.proname, pg_get_function_identity_arguments(item.oid));
  end loop;
end $$;
create or replace function public.app_notify_verify_rows(p_claim_id uuid, p_ids bigint[])
returns jsonb language sql stable security definer set search_path = public, private, pg_temp as $$
  select coalesce(jsonb_agg(jsonb_build_object('id', v.id, 'verdict', v.verdict, 'reason', v.reason) order by v.id), '[]'::jsonb)
  from (
    select n.id,
           case
             when p_claim_id is null or n.status <> 'sending' or n.claim_id is distinct from p_claim_id or n.lease_expires_at <= now()
               then 'skip'
             when not exists(select 1 from public.settings s where s.id = 1 and n.event = any(s.email_notify_events))
               then 'cancel'
             when not private.app_notify_recipient_allowed(n.recipient_user_id, n.event)
               then 'cancel'
             when a.id is null or a.version is distinct from n.application_version
               then 'cancel'
             when n.event is distinct from private.app_notify_event_for_status(a.status)
               then 'cancel'
             else 'send'
           end as verdict,
           case
             when p_claim_id is null or n.status <> 'sending' or n.claim_id is distinct from p_claim_id or n.lease_expires_at <= now()
               then '该行已不属于本次领取（状态、批次或租约已变化），不再投递'
             when not exists(select 1 from public.settings s where s.id = 1 and n.event = any(s.email_notify_events))
               then '管理员已关闭「' || n.event || '」提醒，本封已作废'
             when not private.app_notify_recipient_allowed(n.recipient_user_id, n.event)
               then '收件人已不具备该待办的处理身份，提醒已作废'
             when a.id is null or a.version is distinct from n.application_version
               then '申请已重新提交（版本 ' || n.application_version || ' → ' || coalesce(a.version::text, '已删除') || '），提醒已作废'
             when n.event is distinct from private.app_notify_event_for_status(a.status)
               then '申请状态已不再是「' || n.event || '」对应的状态（当前 ' || a.status || '），提醒已作废'
             else ''
           end as reason
    from public.notifications n
    left join public.applications a on a.id = n.application_id
    where n.id = any(coalesce(p_ids, '{}'::bigint[]))
  ) v;
$$;

-- 永久失败（尝试次数用满）的提醒在配置好邮件服务后可以重新排队；保留 last_error 便于管理员看原因。
create or replace function public.app_reset_failed_notifications(p_actor_id uuid)
returns integer language plpgsql security definer set search_path = public, private, pg_temp as $$
declare reset_count integer;
begin
  if not private.app_user_has_role(p_actor_id, 'admin') then raise exception '没有管理员权限'; end if;
  update public.notifications
     set status = 'pending', attempts = 0, next_attempt_at = now(), lease_expires_at = now(), claim_id = null
   where status = 'failed';
  get diagnostics reset_count = row_count;
  insert into public.audit_logs(actor_id, event, detail, metadata)
  values (p_actor_id, '重置失败邮件提醒', reset_count || ' 封重新排队', jsonb_build_object('数量', reset_count));
  return reset_count;
end $$;

-- 收件人只能由本人写入：p_actor_id 与 p_user_id 必须相同，数据库层也不接受“替别人绑定”；
-- 正文邮箱不进入审计内容。这个文件的前一版就地创建过两参数版本，先按函数名把所有重载删掉
-- （create or replace 改不了签名；留着不同参数个数的重载会让 PostgREST 的命名参数调用变得有歧义）。
do $$
declare item record;
begin
  for item in
    select p.oid, p.proname from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'app_bind_email'
  loop
    execute format('drop function public.%I(%s)', item.proname, pg_get_function_identity_arguments(item.oid));
  end loop;
end $$;
create or replace function public.app_bind_email(p_actor_id uuid, p_user_id uuid, p_email text)
returns void language plpgsql security definer set search_path = public, private, pg_temp as $$
declare normalized text := lower(trim(coalesce(p_email, '')));
begin
  if p_actor_id is null or p_user_id is null or p_actor_id <> p_user_id then raise exception '只能绑定自己的邮箱'; end if;
  if char_length(normalized) > 254 then raise exception '邮箱地址过长'; end if;
  if normalized <> '' and normalized !~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$' then raise exception '邮箱格式不正确'; end if;
  update public.app_users set email = nullif(normalized, ''), updated_at = now() where id = p_user_id and active;
  if not found then raise exception '账号不存在或已停用'; end if;
  insert into public.audit_logs(actor_id, event, detail)
  values (p_user_id, '绑定邮箱', case when normalized = '' then '清除邮箱' else '邮箱已更新' end);
end $$;

-- 只有管理员能改「总开关 + 逐类勾选」。服务端把数组规范化成固定顺序并去重（前端传来的顺序不参与判定），
-- 非枚举值一律拒绝；变更写审计（旧值/新值都记，含总开关与类型清单）。
-- 本文件前一版是两参数签名，先按函数名删掉所有重载，避免 PostgREST 命名参数调用出现歧义。
do $$
declare item record;
begin
  for item in
    select p.oid, p.proname from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'app_update_email_notify'
  loop
    execute format('drop function public.%I(%s)', item.proname, pg_get_function_identity_arguments(item.oid));
  end loop;
end $$;
create or replace function public.app_update_email_notify(p_actor_id uuid, p_enabled boolean, p_events text[])
returns void language plpgsql security definer set search_path = public, private, pg_temp as $$
declare old_value boolean; old_events text[]; normalized text[];
begin
  if not private.app_user_has_role(p_actor_id, 'admin') or p_enabled is null then raise exception '没有管理员权限或参数无效'; end if;
  if p_events is null or exists(
       select 1 from unnest(p_events) e
       where e is null or e not in ('待财委审批','待主席审批','退回修改','待补充收款码','待付款登记','拒绝申请','已付款')) then
    raise exception '提醒类型无效';
  end if;
  select coalesce(array_agg(e order by ord), '{}'::text[]) into normalized
  from unnest(array['待财委审批','待主席审批','退回修改','待补充收款码','待付款登记','拒绝申请','已付款']) with ordinality as t(e, ord)
  where e = any(p_events);
  select email_notify_enabled, email_notify_events into old_value, old_events from public.settings where id = 1 for update;
  update public.settings
     set email_notify_enabled = p_enabled, email_notify_events = normalized, updated_at = now(), updated_by = p_actor_id
   where id = 1;
  insert into public.audit_logs(actor_id, event, detail, metadata)
  values (p_actor_id, '修改邮件通知设置',
    left(case when p_enabled then '开启邮件通知' else '关闭邮件通知' end || '：' ||
      case when cardinality(normalized) = 0 then '未勾选任何提醒类型' else array_to_string(normalized, '、') end, 200),
    jsonb_build_object(
      '总开关', jsonb_build_object('原值', old_value, '新值', p_enabled),
      '提醒类型', jsonb_build_object('原值', to_jsonb(old_events), '新值', to_jsonb(normalized))));
end $$;

-- 管理员建号时可选代填邮箱；旧签名按函数名整体删除（与 app_bind_email / app_claim_notifications /
-- app_update_email_notify 一致）：只删某个写死的参数列表的话，将来出现别的参数个数时库里会同时留两个候选，
-- PostgREST 的命名参数调用会报 PGRST203（could not choose the best candidate function）。
-- p_email 保留默认值是为了让 supabase/admin-settings-audit.verify.sql 的六参数写法继续可跑；
-- app-api 通过 PostgREST 以命名参数调用，始终带上 p_email，因此不会被旧重载抢走。
do $$
declare item record;
begin
  for item in
    select p.oid, p.proname from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'app_admin_create_user'
  loop
    execute format('drop function public.%I(%s)', item.proname, pg_get_function_identity_arguments(item.oid));
  end loop;
end $$;
create or replace function public.app_admin_create_user(p_actor_id uuid, p_username text, p_password text, p_full_name text, p_department text, p_roles text[], p_email text default '')
returns jsonb language plpgsql security definer set search_path = public, private, pg_temp as $$
declare u jsonb; normalized text := lower(trim(coalesce(p_email, '')));
begin
  if not private.app_user_has_role(p_actor_id, 'admin') then raise exception '没有管理员权限'; end if;
  if exists(select 1 from unnest(coalesce(p_roles, '{}'::text[])) r where r is null or r not in ('finance','chair','admin')) then raise exception '角色无效'; end if;
  if char_length(normalized) > 254 or (normalized <> '' and normalized !~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$') then raise exception '邮箱格式不正确'; end if;
  u := private.app_insert_user(p_username, p_password, p_full_name, p_department);
  if normalized <> '' then update public.app_users set email = normalized, updated_at = now() where id = (u->>'id')::uuid; end if;
  perform public.app_set_member_roles(p_actor_id, (u->>'id')::uuid, p_roles, true);
  insert into public.audit_logs(actor_id, event, detail, metadata)
  values (p_actor_id, '添加用户', '创建 @' || (u->>'username') || '（' || (u->>'full_name') || '）',
    jsonb_build_object('target_user_id', u->>'id', 'target_username', u->>'username', 'roles', p_roles, 'email_bound', normalized <> ''));
  return u;
end $$;

revoke all on function public.app_bind_email(uuid, uuid, text) from public, anon, authenticated;
revoke all on function public.app_update_email_notify(uuid, boolean, text[]) from public, anon, authenticated;
revoke all on function public.app_claim_notifications(uuid, integer, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.app_notify_verify_rows(uuid, bigint[]) from public, anon, authenticated;
revoke all on function public.app_reset_failed_notifications(uuid) from public, anon, authenticated;
revoke all on function public.app_admin_create_user(uuid, text, text, text, text, text[], text) from public, anon, authenticated;
grant execute on function public.app_bind_email(uuid, uuid, text) to service_role;
grant execute on function public.app_update_email_notify(uuid, boolean, text[]) to service_role;
grant execute on function public.app_claim_notifications(uuid, integer, integer, integer, integer) to service_role;
grant execute on function public.app_notify_verify_rows(uuid, bigint[]) to service_role;
grant execute on function public.app_reset_failed_notifications(uuid) to service_role;
grant execute on function public.app_admin_create_user(uuid, text, text, text, text, text[], text) to service_role;
