create extension if not exists pgcrypto;
create schema if not exists private;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text not null default '',
  department text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('finance','chair','cashier','admin')),
  primary key (user_id, role)
);

create table if not exists public.settings (
  id integer primary key check (id = 1),
  threshold numeric(12,2) not null default 100.00 check (threshold > 0),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id)
);

create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id),
  title text not null check (char_length(title) between 1 and 120),
  purpose text not null check (char_length(purpose) between 1 and 5000),
  amount numeric(12,2) not null check (amount > 0 and amount <= 10000000),
  category text not null check (char_length(category) between 1 and 80),
  department text not null check (char_length(department) between 1 and 80),
  use_date date not null,
  status text not null default 'draft' check (status in ('draft','finance_pending','chair_pending','changes_requested','rejected','payment_info_required','payment_pending','paid','cancelled')),
  version integer not null default 0 check (version >= 0),
  rule_threshold numeric(12,2),
  recipient text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.application_files (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.applications(id) on delete cascade,
  owner_id uuid not null references public.profiles(id),
  kind text not null check (kind in ('attachment','qr','receipt')),
  storage_path text not null unique,
  name text not null,
  mime text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.approval_actions (
  id bigint generated by default as identity primary key,
  application_id uuid not null references public.applications(id) on delete cascade,
  version integer not null,
  actor_id uuid not null references public.profiles(id),
  action text not null,
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  application_id uuid primary key references public.applications(id) on delete cascade,
  amount numeric(12,2) not null,
  reference text not null unique,
  actor_id uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id),
  event text not null,
  detail text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists applications_owner_updated_idx on public.applications(owner_id, updated_at desc);
create index if not exists applications_status_updated_idx on public.applications(status, updated_at desc);
create index if not exists approval_actions_application_idx on public.approval_actions(application_id, id desc);
create index if not exists application_files_application_idx on public.application_files(application_id, created_at);

insert into public.settings(id, threshold) values (1, 100.00) on conflict (id) do nothing;

create or replace function private.has_role(p_user_id uuid, p_role text)
returns boolean language sql stable security definer set search_path = public, private, pg_temp as $$
  select p_user_id is not null and exists(select 1 from public.user_roles where user_id = p_user_id and role = p_role);
$$;
create or replace function private.has_any_role(p_user_id uuid)
returns boolean language sql stable security definer set search_path = public, private, pg_temp as $$
  select p_user_id is not null and exists(select 1 from public.user_roles where user_id = p_user_id);
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  insert into public.profiles(id, full_name, email)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)), coalesce(new.email, ''))
  on conflict (id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.settings enable row level security;
alter table public.applications enable row level security;
alter table public.application_files enable row level security;
alter table public.approval_actions enable row level security;
alter table public.payments enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated using (id = (select auth.uid()) or (select private.has_any_role((select auth.uid()))));
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));

drop policy if exists roles_read on public.user_roles;
create policy roles_read on public.user_roles for select to authenticated using (user_id = (select auth.uid()) or (select private.has_role((select auth.uid()), 'admin')));

drop policy if exists settings_read on public.settings;
create policy settings_read on public.settings for select to authenticated using (true);

drop policy if exists applications_read on public.applications;
create policy applications_read on public.applications for select to authenticated using (owner_id = (select auth.uid()) or (select private.has_any_role((select auth.uid()))));
drop policy if exists applications_insert on public.applications;
create policy applications_insert on public.applications for insert to authenticated with check (owner_id = (select auth.uid()) and status = 'draft' and version = 0);
drop policy if exists applications_edit_draft on public.applications;
create policy applications_edit_draft on public.applications for update to authenticated using (owner_id = (select auth.uid()) and status in ('draft','changes_requested')) with check (owner_id = (select auth.uid()) and status in ('draft','changes_requested'));

drop policy if exists files_read on public.application_files;
create policy files_read on public.application_files for select to authenticated using (owner_id = (select auth.uid()) or (select private.has_any_role((select auth.uid()))));

drop policy if exists actions_read on public.approval_actions;
create policy actions_read on public.approval_actions for select to authenticated using (exists(select 1 from public.applications a where a.id = application_id and (a.owner_id = (select auth.uid()) or (select private.has_any_role((select auth.uid()))))));

drop policy if exists payments_read on public.payments;
create policy payments_read on public.payments for select to authenticated using (exists(select 1 from public.applications a where a.id = application_id and (a.owner_id = (select auth.uid()) or (select private.has_any_role((select auth.uid()))))));

drop policy if exists audit_admin_read on public.audit_logs;
create policy audit_admin_read on public.audit_logs for select to authenticated using ((select private.has_role((select auth.uid()), 'admin')));

insert into storage.buckets (id, name, public) values ('application-files', 'application-files', false) on conflict (id) do nothing;
drop policy if exists application_files_insert on storage.objects;
create policy application_files_insert on storage.objects for insert to authenticated with check (bucket_id = 'application-files' and (split_part(name, '/', 1) = (select auth.uid())::text or (select private.has_any_role((select auth.uid())))));
drop policy if exists application_files_read on storage.objects;
create policy application_files_read on storage.objects for select to authenticated using (bucket_id = 'application-files' and exists(select 1 from public.application_files f where f.storage_path = name and (f.owner_id = (select auth.uid()) or (select private.has_any_role((select auth.uid()))))));
drop policy if exists application_files_delete on storage.objects;
create policy application_files_delete on storage.objects for delete to authenticated using (bucket_id = 'application-files' and (split_part(name, '/', 1) = (select auth.uid())::text or (select private.has_role((select auth.uid()), 'admin'))));

create or replace function public.claim_first_admin()
returns boolean language plpgsql security definer set search_path = public, private, pg_temp as $$
begin
  if auth.uid() is null then return false; end if;
  if not exists(select 1 from public.user_roles) then
    insert into public.user_roles(user_id, role) values (auth.uid(), 'admin') on conflict do nothing;
    insert into public.audit_logs(actor_id, event, detail) values (auth.uid(), '首次账号成为管理员', '');
    return true;
  end if;
  return false;
end;
$$;

create or replace function public.submit_application(p_application_id uuid, p_note text default '')
returns void language plpgsql security definer set search_path = public, private, pg_temp as $$
declare a public.applications%rowtype; threshold_value numeric(12,2); next_version integer;
begin
  select * into a from public.applications where id = p_application_id for update;
  if a.id is null or a.owner_id <> auth.uid() or a.status not in ('draft','changes_requested') then raise exception '当前申请不能提交'; end if;
  select threshold into threshold_value from public.settings where id = 1;
  next_version := a.version + 1;
  update public.applications set status = 'finance_pending', version = next_version, rule_threshold = threshold_value, updated_at = now() where id = a.id;
  insert into public.approval_actions(application_id, version, actor_id, action, note) values (a.id, next_version, auth.uid(), '提交申请', coalesce(p_note, ''));
  insert into public.audit_logs(actor_id, event, detail) values (auth.uid(), '提交申请', a.id::text);
end;
$$;

create or replace function private.review_application(p_application_id uuid, p_decision text, p_note text)
returns void language plpgsql security definer set search_path = public, private, pg_temp as $$
declare a public.applications%rowtype; next_status text; reviewer_role text;
begin
  if length(coalesce(p_note, '')) = 0 then raise exception '请填写处理意见'; end if;
  select * into a from public.applications where id = p_application_id for update;
  if a.id is null or a.owner_id = auth.uid() then raise exception '不能处理此申请'; end if;
  reviewer_role := case when a.status = 'finance_pending' then 'finance' when a.status = 'chair_pending' then 'chair' else null end;
  if reviewer_role is null or not private.has_role(auth.uid(), reviewer_role) then raise exception '没有对应处理权限'; end if;
  if p_decision = 'approve' then
    next_status := case when reviewer_role = 'finance' and a.amount >= a.rule_threshold then 'chair_pending' else 'payment_info_required' end;
  elsif p_decision = 'return' then next_status := 'changes_requested';
  elsif p_decision = 'reject' then next_status := 'rejected';
  else raise exception '未知处理方式';
  end if;
  update public.applications set status = next_status, updated_at = now() where id = a.id;
  insert into public.approval_actions(application_id, version, actor_id, action, note) values (a.id, a.version, auth.uid(), case p_decision when 'approve' then '审批通过' when 'return' then '退回修改' else '拒绝申请' end, p_note);
  insert into public.audit_logs(actor_id, event, detail) values (auth.uid(), '处理申请', a.id::text || ':' || p_decision);
end;
$$;

create or replace function public.approve_application(p_application_id uuid, p_note text) returns void language sql security definer set search_path = public, private, pg_temp as $$ select private.review_application(p_application_id, 'approve', p_note); $$;
create or replace function public.return_application(p_application_id uuid, p_note text) returns void language sql security definer set search_path = public, private, pg_temp as $$ select private.review_application(p_application_id, 'return', p_note); $$;
create or replace function public.reject_application(p_application_id uuid, p_note text) returns void language sql security definer set search_path = public, private, pg_temp as $$ select private.review_application(p_application_id, 'reject', p_note); $$;

create or replace function public.cancel_application(p_application_id uuid, p_note text default '')
returns void language plpgsql security definer set search_path = public, private, pg_temp as $$
declare a public.applications%rowtype;
begin
  select * into a from public.applications where id = p_application_id for update;
  if a.id is null or a.owner_id <> auth.uid() or a.status not in ('draft','changes_requested','finance_pending','chair_pending') then raise exception '当前申请不能撤回'; end if;
  update public.applications set status = 'cancelled', updated_at = now() where id = a.id;
  insert into public.approval_actions(application_id, version, actor_id, action, note) values (a.id, a.version, auth.uid(), '撤回申请', p_note);
end;
$$;

create or replace function public.add_application_file(p_application_id uuid, p_kind text, p_storage_path text, p_name text, p_mime text)
returns uuid language plpgsql security definer set search_path = public, private, pg_temp as $$
declare a public.applications%rowtype; file_id uuid;
begin
  select * into a from public.applications where id = p_application_id;
  if a.id is null or a.owner_id <> auth.uid() or a.status not in ('draft','changes_requested') or p_kind <> 'attachment' then raise exception '当前不能添加附件'; end if;
  insert into public.application_files(application_id, owner_id, kind, storage_path, name, mime) values (a.id, a.owner_id, p_kind, p_storage_path, left(p_name, 180), p_mime) returning id into file_id;
  return file_id;
end;
$$;

create or replace function public.submit_payment_info(p_application_id uuid, p_recipient text, p_storage_path text, p_name text, p_mime text)
returns void language plpgsql security definer set search_path = public, private, pg_temp as $$
declare a public.applications%rowtype;
begin
  select * into a from public.applications where id = p_application_id for update;
  if a.id is null or a.owner_id <> auth.uid() or a.status <> 'payment_info_required' or length(trim(p_recipient)) = 0 then raise exception '当前不能提交收款信息'; end if;
  insert into public.application_files(application_id, owner_id, kind, storage_path, name, mime) values (a.id, a.owner_id, 'qr', p_storage_path, left(p_name, 180), p_mime);
  update public.applications set recipient = left(trim(p_recipient), 80), status = 'payment_pending', updated_at = now() where id = a.id;
  insert into public.approval_actions(application_id, version, actor_id, action, note) values (a.id, a.version, auth.uid(), '提交收款信息', trim(p_recipient));
end;
$$;

create or replace function public.record_payment(p_application_id uuid, p_reference text, p_storage_path text, p_name text, p_mime text)
returns void language plpgsql security definer set search_path = public, private, pg_temp as $$
declare a public.applications%rowtype;
begin
  select * into a from public.applications where id = p_application_id for update;
  if a.id is null or a.owner_id = auth.uid() or a.status <> 'payment_pending' or (not private.has_role(auth.uid(), 'cashier') and not private.has_role(auth.uid(), 'admin')) then raise exception '当前不能登记付款'; end if;
  insert into public.payments(application_id, amount, reference, actor_id) values (a.id, a.amount, left(trim(p_reference), 120), auth.uid());
  insert into public.application_files(application_id, owner_id, kind, storage_path, name, mime) values (a.id, a.owner_id, 'receipt', p_storage_path, left(p_name, 180), p_mime);
  update public.applications set status = 'paid', updated_at = now() where id = a.id;
  insert into public.approval_actions(application_id, version, actor_id, action, note) values (a.id, a.version, auth.uid(), '登记人工付款', trim(p_reference));
end;
$$;

create or replace function public.update_approval_threshold(p_threshold numeric)
returns void language plpgsql security definer set search_path = public, private, pg_temp as $$
begin
  if not private.has_role(auth.uid(), 'admin') or p_threshold <= 0 or p_threshold > 10000000 then raise exception '没有权限或金额无效'; end if;
  update public.settings set threshold = round(p_threshold, 2), updated_at = now(), updated_by = auth.uid() where id = 1;
  insert into public.audit_logs(actor_id, event, detail) values (auth.uid(), '更新审批门槛', round(p_threshold, 2)::text);
end;
$$;

create or replace function public.set_member_roles(p_user_id uuid, p_roles text[], p_active boolean)
returns void language plpgsql security definer set search_path = public, private, pg_temp as $$
begin
  if not private.has_role(auth.uid(), 'admin') or p_user_id = auth.uid() or exists(select 1 from unnest(p_roles) r where r not in ('finance','chair','cashier','admin')) then raise exception '没有权限或角色无效'; end if;
  update public.profiles set active = p_active where id = p_user_id;
  delete from public.user_roles where user_id = p_user_id;
  insert into public.user_roles(user_id, role) select p_user_id, r from unnest(p_roles) r;
  insert into public.audit_logs(actor_id, event, detail) values (auth.uid(), '更新成员权限', p_user_id::text);
end;
$$;

revoke all on function public.claim_first_admin() from public;
revoke all on function public.submit_application(uuid, text) from public;
revoke all on function public.approve_application(uuid, text) from public;
revoke all on function public.return_application(uuid, text) from public;
revoke all on function public.reject_application(uuid, text) from public;
revoke all on function public.cancel_application(uuid, text) from public;
revoke all on function public.add_application_file(uuid, text, text, text, text) from public;
revoke all on function public.submit_payment_info(uuid, text, text, text, text) from public;
revoke all on function public.record_payment(uuid, text, text, text, text) from public;
revoke all on function public.update_approval_threshold(numeric) from public;
revoke all on function public.set_member_roles(uuid, text[], boolean) from public;
grant execute on function public.claim_first_admin() to authenticated;
grant execute on function public.submit_application(uuid, text) to authenticated;
grant execute on function public.approve_application(uuid, text) to authenticated;
grant execute on function public.return_application(uuid, text) to authenticated;
grant execute on function public.reject_application(uuid, text) to authenticated;
grant execute on function public.cancel_application(uuid, text) to authenticated;
grant execute on function public.add_application_file(uuid, text, text, text, text) to authenticated;
grant execute on function public.submit_payment_info(uuid, text, text, text, text) to authenticated;
grant execute on function public.record_payment(uuid, text, text, text, text) to authenticated;
grant execute on function public.update_approval_threshold(numeric) to authenticated;
grant execute on function public.set_member_roles(uuid, text[], boolean) to authenticated;
