// 真实 PostgreSQL（PGlite，WASM）里跑完整套 SQL 栈的共享加载器。
// 加载顺序、平台占位（auth/storage/角色）与内置 admin 夹具与 tests/sql-migrations.test.mjs 完全一致：
// 那个文件负责断言"整套栈能按文档顺序跑完"，这里只把同一段加载逻辑抽出来给别的测试复用 SQL 栈。
//   1) 基线段迁移：20260929130000_funds.sql 建 profiles/user_roles/settings/applications/... 与 storage bucket；
//      20260929180000_custom_app_users.sql 建 app_users/app_sessions。散装 SQL 改的就是这些表。
//      20261002133000 与 20261005010000 只重定义 private.app_user_has_role，放这里更贴近"库里本来就有完整账本"。
//   2) 4 份散装 SQL（private.app_insert_user、public.app_list_members、显式提交等）。
//   3) 内置 admin 账号（必须夹在 admin-settings-audit.sql 与 member-management-and-resubmission.sql 之间：
//      后者会装上锁死 admin 角色的触发器，之后再补角色就会被拒）。
//   4) 其余迁移：20261004210000_email_notify.sql 开头的 fail-fast 明确要求散装 SQL 先执行。
//   5) 全部同名 .verify.sql（各自包在 begin; … rollback; 里，不留下验证数据）。
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { PGlite } from '@electric-sql/pglite';
import { pgcrypto } from '@electric-sql/pglite/contrib/pgcrypto';

export const SQL_STACK_TIMEOUT = 120000;

const ROOT = import.meta.dirname ? path.resolve(import.meta.dirname, '..', '..') : process.cwd();
const SQL_ROOT = path.join(ROOT, 'supabase');
export const fromRoot = (absolute) => path.relative(ROOT, absolute).split(path.sep).join('/');
export const readSql = (absolute) => readFileSync(absolute, 'utf8');
export const rootPath = (...parts) => path.join(ROOT, ...parts);

// 真实的 Supabase 里 auth/storage schema 与 anon/authenticated/service_role 角色由平台提供，
// PGlite 里没有。这里只建"让迁移里的建表、建策略、授权语句能解析"的最小占位，不模拟任何 Supabase 行为。
const PLATFORM_PLACEHOLDER = `
do $$
begin
  if not exists(select 1 from pg_roles where rolname = 'anon') then create role anon nologin; end if;
  if not exists(select 1 from pg_roles where rolname = 'authenticated') then create role authenticated nologin; end if;
  if not exists(select 1 from pg_roles where rolname = 'service_role') then create role service_role nologin; end if;
end $$;

create schema if not exists auth;
create schema if not exists storage;

-- 迁移里的 on_auth_user_created 触发器与 handle_new_user() 用到 id/email/raw_user_meta_data。
create table if not exists auth.users (
  id uuid primary key default gen_random_uuid(),
  email text,
  raw_user_meta_data jsonb not null default '{}'::jsonb
);
-- 20260929130000_funds.sql 的旧 RLS 策略直接调用 auth.uid()；这里只要能被解析。
create or replace function auth.uid() returns uuid language sql stable as $$ select null::uuid $$;

-- 20260929130000_funds.sql 会往 storage.buckets 插 bucket，并在 storage.objects 上建策略与 revoke。
create table if not exists storage.buckets (
  id text primary key,
  name text not null,
  public boolean not null default false,
  file_size_limit bigint,
  allowed_mime_types text[]
);
create table if not exists storage.objects (
  id uuid primary key default gen_random_uuid(),
  bucket_id text references storage.buckets(id),
  name text,
  owner uuid,
  created_at timestamptz not null default now()
);
alter table storage.objects enable row level security;

-- cron 桩：只提供 pg_cron 的 cron.job 表与 schedule/unschedule 两个函数。
-- 真实的 pg_cron 在 PGlite 里装不上（pg_available_extensions 里没有它，迁移会走"跳过"分支），
-- 但有了这个桩，email_notify_cron.verify.sql 就能直接调 private.app_schedule_email_cron，
-- 真正验证任务名/周期/x-app-cron 头/pg_net 超时写对了——否则那几条断言永远不会执行。
create schema if not exists cron;
create table if not exists cron.job (
  jobid bigint generated by default as identity primary key,
  jobname text,
  schedule text,
  command text,
  active boolean not null default true
);
create or replace function cron.schedule(job_name text, schedule text, command text) returns bigint
  language plpgsql as $$
  declare new_id bigint;
  begin
    insert into cron.job(jobname, schedule, command) values (job_name, schedule, command) returning jobid into new_id;
    return new_id;
  end $$;
create or replace function cron.unschedule(job_id bigint) returns boolean
  language plpgsql as $$
  begin
    delete from cron.job where jobid = job_id;
    return found;
  end $$;
`;

// supabase/migrations 下按 14 位时间戳升序的全部迁移（不含 .verify.sql）。
const MIGRATION_FILES = (() => {
  const directory = path.join(SQL_ROOT, 'migrations');
  return readdirSync(directory)
    .filter((name) => name.endsWith('.sql') && !name.endsWith('.verify.sql'))
    .sort()
    .map((name) => path.join(directory, name));
})();

// docs/database-migrations.md 的 4 份散装 SQL：早期在 Supabase Dashboard 的 SQL 编辑器里手工执行过。
const BULK_FILES = [
  path.join(SQL_ROOT, 'admin-settings-audit.sql'),
  path.join(SQL_ROOT, 'member-management-and-resubmission.sql'),
  path.join(SQL_ROOT, 'detailed-file-and-review-audit.sql'),
  path.join(SQL_ROOT, 'explicit-submission.sql'),
];

const BASELINE_MIGRATIONS = MIGRATION_FILES.filter((file) => {
  const name = path.basename(file);
  return /^(20260929130000|20260929130500|20260929180000|20260929181000|20260929190000|20261002133000|20261005010000)_/.test(name);
});
const LATE_MIGRATIONS = MIGRATION_FILES.filter((file) => !BASELINE_MIGRATIONS.includes(file));

// 散装 SQL 的 verify 脚本以"内置 admin 账号存在"为前置条件，但只按角色取账号、不负责创建。
const ADMIN_FIXTURE = `
do $$
declare super_id uuid;
begin
  select id into super_id from public.app_users where lower(username) = 'admin';
  if super_id is null then
    super_id := (private.app_insert_user('admin', 'Admin-only-1369666', '内置管理员', '管理') ->> 'id')::uuid;
    insert into public.user_roles(user_id, role) values (super_id, 'admin');
  end if;
  update public.settings set registration_enabled = false where id = 1;
end $$;
`;

const VERIFY_FILES = [
  ...BULK_FILES.map((file) => file.replace(/\.sql$/, '.verify.sql')),
  ...MIGRATION_FILES.map((file) => file.replace(/\.sql$/, '.verify.sql')),
].filter(existsSync);

// 最终执行顺序：基线段 → 4 份散装 SQL → 内置 admin → 其余迁移 → 全部 verify（每个文件只执行一次）。
export const EXECUTION_ORDER = [...BASELINE_MIGRATIONS, ...BULK_FILES, ...LATE_MIGRATIONS, ...VERIFY_FILES];

function failure(file, error) {
  const lines = [`执行 ${fromRoot(file)} 失败`, `原始报错：${error.message}`];
  if (error.position) lines.push(`位置：${error.position}`);
  if (error.detail) lines.push(`detail：${error.detail}`);
  if (error.hint) lines.push(`hint：${error.hint}`);
  if (error.where) lines.push(`where：${error.where}`);
  const wrapped = new Error(lines.join('\n'));
  wrapped.cause = error;
  return wrapped;
}

/**
 * 建一个内存 PGlite 实例并把整套 SQL 栈执行一遍。
 * 返回 { db, executed, migrationFiles, bulkFiles, verifyFiles }；失败时关掉实例并抛出带文件名的错误。
 */
export async function createSqlStack() {
  const db = new PGlite({ extensions: { pgcrypto } });
  db.waitReady.catch(() => {});
  const executed = [];
  const runFile = async (file) => {
    const startedAt = Date.now();
    try {
      await db.exec(readSql(file));
    } catch (error) {
      throw failure(file, error);
    }
    executed.push({ file: fromRoot(file), ms: Date.now() - startedAt });
  };
  try {
    await db.exec(PLATFORM_PLACEHOLDER);
    for (const file of BASELINE_MIGRATIONS) await runFile(file);
    await runFile(BULK_FILES[0]);
    await db.exec(ADMIN_FIXTURE);
    for (const file of BULK_FILES.slice(1)) await runFile(file);
    for (const file of LATE_MIGRATIONS) await runFile(file);
    for (const file of VERIFY_FILES) await runFile(file);
  } catch (error) {
    // 起不来的实例留着只会拖住事件循环。
    await db.close().catch(() => {});
    throw error;
  }
  return {
    db,
    executed,
    migrationFiles: MIGRATION_FILES.map(fromRoot),
    bulkFiles: BULK_FILES.map(fromRoot),
    verifyFiles: VERIFY_FILES.map(fromRoot),
  };
}
